<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Folder;
use App\Models\Notes;
use App\Models\Projects;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        if (!$user) {
            $this->command->error("No users found. Please seed users first.");
            return;
        }

        $project = Projects::create([
            'user_id' => $user->id,
            'title' => 'New Writing Project',
            'description' => 'Generated by Seeder',
            'status' => 'draft',
        ]);

        $folders = [
            'Chapters',
            'Characters',
            'World Building',
        ];

        foreach ($folders as $i => $folderName) {
            Folder::create([
                'project_id' => $project->id,
                'name' => $folderName,
                'position' => $i,
            ]);
        }

        Notes::create([
            'user_id' => $user->id,
            'project_id' => $project->id,
            'title' => 'Sinopsis',
            'position' => 0,
        ]);

        $this->command->info("Default project seeded for user: {$user->email}");
    }
}

